//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AteaWeb.Models
{
    using System;
    using System.Collections.Generic;

    // DB-first genererad entity av ADO modell.
    public partial class MessageEntity
    {
        public int MessageId { get; set; }
        public string MessageText { get; set; }
        public System.DateTime MessageTime { get; set; }
    }
}
